# Generated by Django 4.1.7 on 2023-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('chart', models.CharField(choices=[('FD', 'Full day'), ('PT', 'Part-time'), ('PJ', 'Project'), ('FD or PT', 'May be Full day or Part-time')], max_length=40)),
                ('duties', models.TextField()),
                ('requirements', models.TextField()),
                ('conditions', models.TextField()),
                ('online', models.BooleanField()),
                ('available', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
